config/routes.rb
Rails.application.routes.draw do
  
  get 'enviar_correo' => 'frutosecos#enviar_correo'
  
  resources :listacorreos
  
  
  resources :frutosecos

   root 'frutosecos#index'

end

app/models/frutoseco.rb
class Frutoseco < ActiveRecord::Base
  validates_presence_of :nombrefrutoseco, :preciofrutoseco
  validates :preciofrutoseco, :numericality => { :greater_than => 0 }
end

app/controllers/frutosecos_controller.rb
# coding: utf-8
class FrutosecosController < ApplicationController
  #http_basic_authenticate_with name: "vicente", password: "vicente"#, except: :index
  #http_basic_authenticate_with name: "vicente", password: "vicente", except: :index
  before_action :set_frutoseco, only: [:show, :edit, :update, :destroy]
  #before_update :copiar_registro
  
  #========================================================================================================================================================================
  def enviar_correo
    UserNotifier.test_email.deliver_now
    #UserNotifier.rellenar_y_enviar
    respond_to do |format|
      #nos pasamos a AJAX!
      #format.html { #redirect_to :root, :flash => { :success => 'Correo(s) enviado(s) con exito' } }
      #Necesario para mostrar el aviso
      format.js { flash.now[:success] = 'Correo(s) enviado(s) con exito' }
    end
  end
  #========================================================================================================================================================================
  # GET /frutosecos
  # GET /frutosecos.json
  def index
    @frutosecos = Frutoseco.all
    #@frutoseco = Frutoseco.find(params[:id])
  end
  #========================================================================================================================================================================
  # GET /frutosecos/1
  # GET /frutosecos/1.json
  def show
  end
  #========================================================================================================================================================================
  # GET /frutosecos/new
  def new
    @frutoseco = Frutoseco.new
  end
  #========================================================================================================================================================================
  # GET /frutosecos/1/edit
  def edit
    #redirect_to :root
    respond_to do |format|
      format.html { redirect_to :root} 
      format.js   {render :js => "window.location = '/frutosecos'" }#{ redirect_to :root}
    end
  end
  #========================================================================================================================================================================
  # POST /frutosecos
  # POST /frutosecos.json
  def create
    @frutoseco = Frutoseco.new(frutoseco_params)

    respond_to do |format|
      if @frutoseco.save
        format.html { redirect_to @frutoseco, notice: 'Frutoseco was successfully created.' }
        format.json { render :show, status: :created, location: @frutoseco }
      else
        format.html { render :new }
        format.json { render json: @frutoseco.errors, status: :unprocessable_entity }
      end
    end
  end
  #========================================================================================================================================================================
  # PATCH/PUT /frutosecos/1
  # PATCH/PUT /frutosecos/1.json
  def update #+ Histórico
    
    #Historico > Copia de registro antes del update
    copia = @frutoseco.dup
   
    respond_to do |format|      
      if @frutoseco.update(frutoseco_params)
        
         #Historico > Se añade la linea a la tabla Historico
         Historico.create(copia.attributes)
        
        #copia.save -> esto hace que se cree un nuevo row en Frutoseco. noooooo
        
        format.html { redirect_to :root, :flash => { :success => 'El precio de la almendra ' + @frutoseco.nombrefrutoseco + ' ha sido actualizado' }}
        format.js   { redirect_to :root }
        format.json
        
        #format.js { redirect_to root_url }
        #format.json { render :show, status: :ok, location: @frutoseco }
      else
        format.html { render 'error' }
        format.json { render json: @frutoseco.errors, status: :unprocessable_entity }
      end
    end
  end
  #========================================================================================================================================================================
  # ----------------------------------------------------------------------------------
  #no se usa ya, cambiado por form_for :remote => true
  #ya no uso form_for :remote => true por el rollo de no ver las notificaciones.
  def update_ajax
      @frutoseco = Frutoseco.find(params[:id])
        
      precio = params[:preciofrutoseco]
      
      @frutoseco.preciofrutoseco = precio
      
      logger.info 'Cucu'
      logger.info params[:frutoseco][:preciofrutoseco]
      
      #@frutoseco.save
      
      respond_to do |format|
      if @frutoseco.update(frutoseco_update_params)
        #format.js { render 'update_ajax', status: :ok, location: @frutoseco }
        format.js { redirect_to root }
        format.html { redirect_to root }
      else
        format.js { render json: @frutoseco.errors, status: :unprocessable_entity }
      end
    end
  end
  #========================================================================================================================================================================
  # ----------------------------------------------------------------------------------
  # DELETE /frutosecos/1
  # DELETE /frutosecos/1.json
  def destroy
    @frutoseco.destroy
    respond_to do |format|
      format.html { redirect_to frutosecos_url, notice: 'Frutoseco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
#========================================================================================================================================================================
#========================================================================================================================================================================
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frutoseco
      @frutoseco = Frutoseco.find(params[:id])
    end
#========================================================================================================================================================================
    # Never trust parameters from the scary internet, only allow the white list through.
    def frutoseco_params
      params.require(:frutoseco).permit(:nombrefrutoseco, :preciofrutoseco)
    end
#========================================================================================================================================================================
#ya no se usa, linkado con update_ajax
    def frutoseco_update_params
      params.permit(:id,:nombrefrutoseco,:preciofrutoseco)
    end 
 #========================================================================================================================================================================
 #Ya no se usa   
  def copiar_registro
    logger.info 'Aqui se copia el registro'
  end
#========================================================================================================================================================================    
end

app/helpers/frutosecos_helper.rb
module FrutosecosHelper
end

app/views/frutosecos/_form.html.erb
<%= form_for(@frutoseco) do |f| %>
  <% if @frutoseco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@frutoseco.errors.count, "error") %> impidieron guardar los datos:</h2>
      <ul>
      <% @frutoseco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Fruto Seco' %>
    <br>
    <%= f.text_field :nombrefrutoseco , :class => 'form-control', :disabled => true %>
  </div>
  
  <div class="form-group">
    <%= f.label 'Precio' %>
    <br>
    <%= f.number_field :preciofrutoseco , :step => "any", :class => 'form-control' %>
  </div>
   
  <br>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/frutosecos/edit.html.erb
<h1>Editar Fruto Seco</h1>

<%= render 'form' %>

<%= link_to 'Ver', @frutoseco %> |
<%= link_to 'Atras', frutosecos_path %>

app/views/frutosecos/enviar_correo.js.erb
<% flash.each do |type, message| %>
  $("#notice").html('<%= j render partial: "shared/flashmessages" %>');
<% end %>

app/views/frutosecos/error.html.erb
<% if @frutoseco.nil? %>
<% else %>
  <% if @frutoseco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@frutoseco.errors.count, "error") %> impidieron guardar los datos:</h2>
      <ul>
      <% @frutoseco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>
  <br>
  <%= link_to 'Ok', frutosecos_path, :class => 'btn btn-primary' %>

app/views/frutosecos/index.html.erb
<script>
/* Muestra el spinner cuando se ejecuta una accion AJAX*/
$( document ).ready(function() {
  // esconder spinner
  $(".spinner").hide();
  // mostrar spinner al iniciarse llamada AJAX
  $(document).ajaxStart(function(){
    $(".spinner").show();
  });
  // esconder spinner al finalizar la llamada AJAX
  $(document).ajaxStop(function(){
    $(".spinner").hide();
  });
});
</script>

<h1 class='jumbotron-mini'>Listado de Precios Actual</h1>

<p id="notice"><%= notice %></p>

<div class="spinner">
  <div class="double-bounce1"></div>
  <div class="double-bounce2"></div>
</div>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Nombre Fruto Seco</th>
      <th>Precio Fruto Seco Actual</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	
    <% @frutosecos.each do |frutoseco| %>
     
     <tr>
     	
        <td><%= frutoseco.nombrefrutoseco %></td>
        
        <td><%= number_to_currency(frutoseco.preciofrutoseco, locale: :es)  %></td>
        
        	<%= form_for(frutoseco) do |f| %>
         
			   	<td><%= f.number_field :preciofrutoseco, :step => "any", onclick: 'this.value=""; return false;', :class => 'form-control', :style => 'width:80px;' %></td>
			       		
			   	<td><%= f.submit "Cambiar Precio", :class => 'btn btn-primary btn-sm'%></td>
       		
        	<% end %>
        
      </tr>  

    <% end %>
    
  </tbody>
  
</table>

<br>        

<table class="table">
	<tr>
		<td>
			<%= link_to 'Lista de Correo', listacorreos_path, :class=>'btn btn-primary btn-block' %>	
		</td>
		<td>
			<%= link_to 'Enviar Correo', {:controller => "frutosecos", :action => "enviar_correo", :remote=>true }, :class=> 'btn btn-primary btn-block' %>	
		</td>
	</tr>
</table>

app/views/frutosecos/new.html.erb
<h1>Nuevo Fruto Seco</h1>

<%= render 'form' %>

<br>

<%= link_to 'Atras', frutosecos_path %>

app/views/frutosecos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre Fruto Seco:</strong>
  <%= @frutoseco.nombrefrutoseco %>
</p>


<p>
  <strong>Precio Fruto Seco:</strong>
  <%= @frutoseco.preciofrutoseco %>
</p>

<%= link_to 'Editar', edit_frutoseco_path(@frutoseco) %> |
<%= link_to 'Atras', frutosecos_path %>