config/routes.rb
Rails.application.routes.draw do
  
  get 'enviar_correo' => 'frutosecos#enviar_correo'
  
  resources :listacorreos
  
  
  resources :frutosecos

   root 'frutosecos#index'

end

app/models/listacorreo.rb
class Listacorreo < ActiveRecord::Base
  validates_presence_of :nombre, :email
  #mu basico
  #validates_format_of :email, :with => /@/
  #un poco mejor
  validates_format_of :email, :with => /.+@.+\..+/i
end

app/controllers/listacorreos_controller.rb
class ListacorreosController < ApplicationController
  before_action :set_listacorreo, only: [:show, :edit, :update, :destroy]

  # GET /listacorreos
  # GET /listacorreos.json
  def index
    @listacorreos = Listacorreo.all
  end

  # GET /listacorreos/1
  # GET /listacorreos/1.json
  def show
  end

  # GET /listacorreos/new
  def new
    @listacorreo = Listacorreo.new
  end

  # GET /listacorreos/1/edit
  def edit
  end

  # POST /listacorreos
  # POST /listacorreos.json
  def create
    @listacorreo = Listacorreo.new(listacorreo_params)

    respond_to do |format|
      if @listacorreo.save
        format.html { redirect_to @listacorreo, :flash => { :success => 'Destinatario de correo actualizado' }}
        format.json { render :show, status: :created, location: @listacorreo }
      else
        format.html { render :new }
        format.json { render json: @listacorreo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listacorreos/1
  # PATCH/PUT /listacorreos/1.json
  def update
    respond_to do |format|
      if @listacorreo.update(listacorreo_params)
        format.html { redirect_to @listacorreo, :flash => { :success => 'Destinatario de correo actualizado' }}
        format.json { render :show, status: :ok, location: @listacorreo }
      else
        format.html { render :edit }
        format.json { render json: @listacorreo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listacorreos/1
  # DELETE /listacorreos/1.json
  def destroy
    @listacorreo.destroy
    respond_to do |format|
      format.html { redirect_to listacorreos_url, notice: 'Destinatario de correo borrado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listacorreo
      @listacorreo = Listacorreo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listacorreo_params
      params.require(:listacorreo).permit(:nombre, :email)
    end
end

app/helpers/listacorreos_helper.rb
module ListacorreosHelper
end

app/views/listacorreos/_form.html.erb
<%= form_for(@listacorreo) do |f| %>
  <% if @listacorreo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listacorreo.errors.count, "error") %> han impedido que se guarden los datos:</h2>

      <ul>
      <% @listacorreo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, :class => 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, :class => 'form-control' %>
  </div>
  
  <div class="actions">
    <%= f.submit (f.object.new_record? ? "Crear Destinatario" : "Actualizar Destinatario"), :class=>'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/listacorreos/edit.html.erb
<h1>Editar</h1>

<div class="well">
		<%= render 'form' %>
		<!-- <%= link_to 'Ver', @listacorreo, :class=>'btn btn-primary btn-block' %> -->
		<%= link_to 'Atras', listacorreos_path, :class=>'btn btn-primary btn-block' %>
</div>

app/views/listacorreos/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="jumbotron">Lista de Correos</h1>

<div class="col-sm-12">

<div class="well">

		<table class="table table-condensed">
			
		  <thead>
		  	
		    <tr>
		      <th>Nombre</th>
		      <th>Email</th>
		      <th colspan="4"></th>
		    </tr>
		  </thead>
		
		  <tbody>
		  	 	
		    <% @listacorreos.each do |listacorreo| %>
		
		      <tr>
		        <td><%= listacorreo.nombre %></td>
		        <td><%= listacorreo.email %></td>
		        <!-- <td><%= link_to 'Ver', listacorreo, :class=>'btn' %></td> -->
		      </tr>
		      
		      <tr>
		        <td><%= link_to 'Editar', edit_listacorreo_path(listacorreo), :class=>'btn btn-primary btn-sm btn-block' %></td>
		        <td><%= link_to 'Borrar', listacorreo, method: :delete, data: { confirm: 'Borrar miembro de la lista. Seguro?' }, :class=>'btn btn-danger btn-sm btn-block' %></td>
		      </tr>
		      
		    <% end %>
		 
		  </tbody>
		</table>
		
</div>
</div>

<br>
<div class="col-sm-12">
<%= link_to 'Nuevo destinatario', new_listacorreo_path, :class=>"btn btn-primary btn-block" %>
<%= link_to 'Volver', root_path, :class=>"btn btn-primary btn-block" %>
</div>

app/views/listacorreos/new.html.erb
<h1>Añadir destinatario a lista de correo</h1>

<div class="well">
	<%= render 'form' %>
	<%= link_to 'Atras', listacorreos_path, :class=>'btn btn-primary btn-block'%>
</div>

app/views/listacorreos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well">
	
		<table class="table table-condensed">
			<thead>
				
				<tr>
				
					<th><strong>Nombre</strong></th><th><strong>Email</strong></th>
							
				</tr>
				
			</thead>
			
			<tbody>
				
				<tr>
		  			<td><%= @listacorreo.nombre %></td><td><%= @listacorreo.email %></td>
				</tr>
		
			</tbody>
		</table>	
		
		<br>
		<br>
		<br>
		
		<%= link_to 'Editar', edit_listacorreo_path(@listacorreo), :class=>'btn btn-primary btn-block'%>
		<%= link_to 'Atras', listacorreos_path, :class=>'btn btn-primary btn-block' %>

</div>